name: OpenWrt K2P CI
on:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    - name: Install - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: openwrt source download
      run: |
        git clone -b openwrt-19.07 https://git.openwrt.org/openwrt/openwrt.git
    - name: Update - openwrt source clean
      run: |
        cd openwrt
        sed -i 's/-SNAPSHOT/.3/g' include/version.mk
        ./scripts/feeds clean -a
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
    - name: Download - openwrt build dependencies
      run: |
        cd openwrt
        make download -j12
    - name: Build - make openwrt source
      run: |
        cd openwrt
        make -j6
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p-build-bin
        path: openwrt/bin/
    - name: Remove - delete packages files
      run: |
        cd openwrt/bin/targets/ramips/mt7621/
        rm -rf packages/
        ls -hl
    - name: Release - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openwrt/bin/targets/ramips/mt7621/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
